version: "3.9"
services:
  postgres:
    build: ./database/
    environment:
      POSTGRES_PASSWORD: securepass
    ports:
    - "5432:5432"
  api:
      build: .
      restart: on-failure
      depends_on:
        - postgres
      ports:
        - "8080:8080"