FROM postgres

#psql --command "CREATE TABLE USERS (cpf varchar(12) primary key, nome varchar(50) not null,\
#                    data_nascimento varchar(10) not null, cep varchar(10) not null, rua varchar(40) not null,\
#                    bairro varchar(40) not null, cidade varchar(30) not null,\
#                    estado varchar(40) not null)"


EXPOSE 5432

